### PR TITLE
Updates to `OWNERS_ALIASES`

### PR DESCRIPTION
**Pull request by jljaco**
remove jaypipes & vijtrip2, add jljaco

**Note**: I'm using this PR to diagnose some outstanding issues with how Prow checks for membership for purposes of approval, `lgtm`, etc.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jaypipes** [comment]
😥

**Comment by RedbackThomson** [comment]
This looks like it's been mixed in with a code-generator update. We can probably remove all files except `OWNERS_ALIASES` and merge

**Pull request closed without merging**
