### PR TITLE
Bump aws-sdk-go version to v1.44.181

### PR DESCRIPTION
**Pull request by Vandita2020**
Description of changes:

- Bump aws-sdk-go version to v1.44.181
- SnapStart addition 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
Before this goes too much deeper into the `SnapStart` work, I'd love to just merge the AWS SDK updates as a separate PR to any new features. That way we can decouple any bugs that come from the new SDK and the ones that were introduced with any SnapStart changes

**Comment by jaypipes** [comment]
@Vandita2020 @RedbackThomson are the tests are failing the SnapStart key check because the [version of the `aws` CLI used by the e2e test scripts](https://github.com/aws-controllers-k8s/test-infra/blob/fc1d5528b4549b33983f67abb5fef1e7a8e920eb/prow/jobs/images/Dockerfile.test#L45-L48) doesn't include new Lambda API changes?

**Comment by RedbackThomson** [comment]
> @Vandita2020 @RedbackThomson are the tests failing the SnapStart key check because the [version of the `aws` CLI used by the e2e test scripts](https://github.com/aws-controllers-k8s/test-infra/blob/fc1d5528b4549b33983f67abb5fef1e7a8e920eb/prow/jobs/images/Dockerfile.test#L45-L48) doesn't include new Lambda API changes?

`boto3` doesn't use the AWS CLI bindings, afaik. But it might be worth updating the `boto3` version separately, anyway. https://github.com/aws-controllers-k8s/test-infra/blob/main/requirements.txt#L1

**Comment by jaypipes** [comment]
> > @Vandita2020 @RedbackThomson are the tests failing the SnapStart key check because the [version of the `aws` CLI used by the e2e test scripts](https://github.com/aws-controllers-k8s/test-infra/blob/fc1d5528b4549b33983f67abb5fef1e7a8e920eb/prow/jobs/images/Dockerfile.test#L45-L48) doesn't include new Lambda API changes?
> 
> `boto3` doesn't use the AWS CLI bindings, afaik. But it might be worth updating the `boto3` version separately, anyway. https://github.com/aws-controllers-k8s/test-infra/blob/main/requirements.txt#L1

Ah, yes, you're totally right, @RedbackThomson. OK, so I do think the boto version needs to be bumped in the requirements.txt file.

**Comment by A-Hilaly** [comment]
Hi @Vandita2020 Thank you for sending this patch! The e2e tests and more specifically the new `snapstart` updates are not working because the [`updateFunctionConfiguration`](https://github.com/aws-controllers-k8s/lambda-controller/blob/main/pkg/resource/function/hooks.go#L122-L124) is not up-to-date, you have to modify it to include the snapstart value in request.

**Comment by A-Hilaly** [comment]
Closed for #75

**Pull request closed without merging**
