### PR TITLE
Add VPCConfig.SecurityId reference

### PR DESCRIPTION
**Pull request by Vandita2020**
Issue #, if available:

Description of changes:
Adding reference for VPCConfig.SecurityId 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
Going to need a rebase, too :)

**Review by A-Hilaly — APPROVED** [review]
Neat! Thank you @Vandita2020 !
/unhold
/lgtm

**Pull request merged**
